### PR TITLE
feat: enable build and hmr for react

### PR DESCRIPTION
**Pull request by arunprabhuk94**
Added `watchPath` and `buildConfig` options to enable live loading of the HTML page on changing the react files inside `src` folder by rebuilding them with the provided `buildConfig`.

### CODE REVIEW

**Comment by aabccd021** [comment]
Thank you!

**Comment by arunprabhuk94** [comment]
@aabccd021 could you publish this as an npm package? We can then add this to the bun's `react` template to fix hot reloading.

**Comment by aabccd021** [comment]
> @aabccd021 could you publish this as an npm package? We can then add this to the bun's `react` template to fix hot reloading.

Sure yes. I will do it when I've got a time. Maybe in a week.

**Comment by aabccd021** [comment]
@arunprabhuk94 it's now published on npm

**Pull request merged**
